Fix the
Exception AttributeError: "'NoneType' object has no attribute 'adj_destroy_adjointer'"

by carefully importing only what is required in sw_config.py